name: CD

on:
    push:
        tags:
            - "[v]?[0-9]+.[0-9]+.[0-9]+"

jobs:
    publish:
        name: Publishing to web
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: Install Rust toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: ${{ matrix.rust }}
                  profile: minimal
                  override: true
            - uses: Swatinem/rust-cache@v1
            - name: Cargo build
              uses: actions-rs/cargo@v1
              with:
                  command: build
                  use-cross: ${{ matrix.job.use-cross }}
                  toolchain: ${{ matrix.rust }}
                  args: --release --target ${{ matrix.job.target }}
